"""empty message

Revision ID: 07c723f96717
Revises: f714741f4d30
Create Date: 2020-12-31 15:40:37.431248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c723f96717'
down_revision = 'f714741f4d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment', sa.Column('studentActive', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment', 'studentActive')
    # ### end Alembic commands ###
