"""empty message

Revision ID: 189df69e6a4e
Revises: 07c723f96717
Create Date: 2020-12-31 15:54:25.189446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189df69e6a4e'
down_revision = '07c723f96717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enrollment', 'studentActive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enrollment', 'studentActive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
