"""empty message

Revision ID: 51855f9a0c6b
Revises: b0b03827b23d
Create Date: 2021-01-24 15:24:06.201435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51855f9a0c6b'
down_revision = 'b0b03827b23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'completed')
    # ### end Alembic commands ###
