"""empty message

Revision ID: 51939f434f4c
Revises: c9c6f9711f68
Create Date: 2020-12-19 23:27:03.297190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51939f434f4c'
down_revision = 'c9c6f9711f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dojo', sa.Column('instructor', sa.Text(), nullable=False))
    op.add_column('student', sa.Column('lastGrading', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'lastGrading')
    op.drop_column('dojo', 'instructor')
    # ### end Alembic commands ###
