"""empty message

Revision ID: b0b03827b23d
Revises: 008a6be7e813
Create Date: 2021-01-20 12:32:11.234180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b03827b23d'
down_revision = '008a6be7e813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentStatus', sa.Column('evaluated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studentStatus', 'evaluated')
    # ### end Alembic commands ###
