"""empty message

Revision ID: ca2656d6dca9
Revises: a5b2ccea1d04
Create Date: 2020-12-28 17:01:30.457294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2656d6dca9'
down_revision = 'a5b2ccea1d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dojo', sa.Column('instructor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'dojo', 'instructor', ['instructor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dojo', type_='foreignkey')
    op.drop_column('dojo', 'instructor_id')
    # ### end Alembic commands ###
